"""Adds repositories/archives needed by stout."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/stout repository. If you encounter it
# anywhere else it is because it has been copied there in order to
# simplify adding transitive dependencies. If you want a different
# version of stout follow the Bazel build instructions at
# https://github.com/3rdparty/stout.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("//3rdparty/bazel-rules-picojson:repos.bzl", picojson_repos = "repos")
load("//3rdparty/bazel-rules-rapidjson:repos.bzl", rapidjson_repos = "repos")

def repos():
    """Adds repositories/archives needed by stout."""
    picojson_repos()

    rapidjson_repos()

    maybe(
        http_archive,
        name = "rules_python",
        sha256 = "4f7e2aa1eb9aa722d96498f5ef514f426c1f55161c3c9ae628c857a7128ceb07",
        strip_prefix = "rules_python-1.0.0",
        url = "https://github.com/bazelbuild/rules_python/releases/download/1.0.0/rules_python-1.0.0.tar.gz",
    )

    maybe(
        http_archive,
        name = "com_google_protobuf",
        sha256 = "955ef3235be41120db4d367be81efe6891c9544b3a71194d80c3055865b26e09",
        strip_prefix = "protobuf-29.5",
        urls = [
            "https://github.com/protocolbuffers/protobuf/archive/v29.5.tar.gz",
        ],
    )

    maybe(
        http_archive,
        name = "com_google_absl",
        sha256 = "f50e5ac311a81382da7fa75b97310e4b9006474f9560ac46f54a9967f07d4ae3",
        strip_prefix = "abseil-cpp-20240722.0",
        urls = [
            "https://storage.googleapis.com/grpc-bazel-mirror/github.com/abseil/abseil-cpp/archive/20240722.0.tar.gz",
            "https://github.com/abseil/abseil-cpp/archive/20240722.0.tar.gz",
        ],
    )

    maybe(
        git_repository,
        name = "com_github_nelhage_rules_boost",
        # That is the last commit before the rules_boost repository was
        # ported to use bzlmod, so we will apply a patch to use GitHub
        # based url link for boost dependencies.
        patches = ["@com_github_3rdparty_stout//bazel:github_url_for_lzma.patch"],
        patch_args = ["-p1"],
        commit = "5d04542e52164931841d06d5a6b3fd2f43c436d0",
        remote = "https://github.com/nelhage/rules_boost",
        shallow_since = "1715450458 +0200",
    )

    maybe(
        http_archive,
        name = "com_github_gflags_gflags",
        url = "https://github.com/gflags/gflags/archive/v2.2.2.tar.gz",
        sha256 = "34af2f15cf7367513b352bdcd2493ab14ce43692d2dcd9dfc499492966c64dcf",
        strip_prefix = "gflags-2.2.2",
    )

    maybe(
        http_archive,
        name = "gtest",
        sha256 = "b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5",
        strip_prefix = "googletest-release-1.11.0",
        url = "https://github.com/google/googletest/archive/release-1.11.0.tar.gz",
    )

    maybe(
        http_archive,
        name = "com_github_google_glog",
        sha256 = "c17d85c03ad9630006ef32c7be7c65656aba2e7e2fbfc82226b7e680c771fc88",
        strip_prefix = "glog-0.7.1",
        urls = ["https://github.com/google/glog/archive/v0.7.1.zip"],
    )

    # Copied and then modified to use the latest 'commit' and 'shallow_since'
    # rather than tracking the 'master' branch from:
    # https://github.com/fmtlib/fmt/tree/master/support/bazel
    maybe(
        git_repository,
        name = "com_github_fmtlib_fmt",
        commit = "81f1cc74a776581cdef8659d176049d3aeb743c6",
        shallow_since = "1658588611 -0700",
        remote = "https://github.com/fmtlib/fmt",
        patch_cmds = [
            "mv support/bazel/.bazelrc .bazelrc",
            "mv support/bazel/.bazelversion .bazelversion",
            "mv support/bazel/BUILD.bazel BUILD.bazel",
            "mv support/bazel/WORKSPACE.bazel WORKSPACE.bazel",
        ],
        # Windows-related patch commands are only needed in the case MSYS2 is not installed.
        # More details about the installation process of MSYS2 on Windows systems can be found here:
        # https://docs.bazel.build/versions/main/install-windows.html#installing-compilers-and-language-runtimes
        # Even if MSYS2 is installed the Windows related patch commands can still be used.
        patch_cmds_win = [
            "Move-Item -Path support/bazel/.bazelrc -Destination .bazelrc",
            "Move-Item -Path support/bazel/.bazelversion -Destination .bazelversion",
            "Move-Item -Path support/bazel/BUILD.bazel -Destination BUILD.bazel",
            "Move-Item -Path support/bazel/WORKSPACE.bazel -Destination WORKSPACE.bazel",
        ],
    )
