name: Check Code Style

# We use action's triggers 'push' and 'pull_request'.
# The strategy is the following: this action will be
# triggered on any push to 'main' branch and any pull
# request to any branch. Thus we avoid duplicate work-
# flows.
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      # Live debug failures using tmate by toggling input parameter
      # 'debug_enabled':
      # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
      # When manually running this workflow:
      # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
      debug_enabled:
        description: "Enable tmate debugging"
        type: boolean
        default: false

jobs:
  check_code_style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # dev-tools/check-code-style uses LLVM14, which
        # isn't easy to install on ubuntu-24.04 (which is
        # ubuntu-latest as of Feb 2025).
        os: ["ubuntu-20.04"]

    steps:
      # We should checkout the repo with submodules
      # cause we need to have symlink to
      # dev-tools/.clang-format file for all code
      # style checks.
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # Call the composite action to check files
      # for correct code style. This action (action.yml)
      # is in `dev-tools` submodule.
      - uses: ./dev-tools/check-code-style
        with:
          os: ${{matrix.os}}

      - name: Debug using tmate (if failure)
        uses: mxschmitt/action-tmate@v3
        # Optionally enable tmate debugging if the workflow was manually-triggered
        # with `debug_enabled` set to `true`.
        # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
