# Workflow for changes that don't need to run build and test.
name: nobuild

on:
  pull_request:
    branches:
      - "main"
    paths:
      - '**.md'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required"'
